#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    h, m, t = map(int, s[:-2].split(':'))
    p = s[-2:] 
    h = h % 12 + (p.upper() == 'PM') * 12
    result = ('%02d:%02d:%02d') % (h, m, t)
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
