#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'hourglassSum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def hourglassSum(arr):
    # Write your code here
    max_=[]
    for i in range(4):
        for j in range(4):
            sum=a[i][j]+a[i][j+1]+a[i][j+2]+a[i+1][j+1]+a[i+2][j]+a[i+2][j+1]+a[i+2][j+2]
            max_.append(sum)
    return max(max_)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = []

    for _ in range(6):
        a.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(a)

    fptr.write(str(result) + '\n')

    fptr.close()
